[package]
name = "mmap-vec"
version = "0.1.0"
edition = "2021"
authors = ["Arthur LE MOIGNE"]
description = "Memory mapped vectors"
license = "MIT"
keywords = ["mmap", "data-strucure"]

[dependencies]
libc = "0.2.147"
uuid = { version = "1.4.1", features = ["v4"] }
