name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install 1.65.0
    - run: rustup override set 1.65.0
    - uses: Swatinem/rust-cache@v2
    - run: rustc --version
    
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run tests (no default features)
      run: cargo test --verbose --no-default-features

    - name: Lint
      run: cargo clippy

    - name: Format
      run: cargo fmt --check
